@startuml

Match *-down-> "2" Player
Match *-down-> "3|5" Set
Match *-down-> Referee

Set *-down-> "6..13" Game

Game <|-down- TieBreakGame


class Match {
- int totalSets
- ArrayList<Set> setsPlayed
- List<Player> players
- boolean isPlayerService
- Game currentGame

+ startNewGame() **
+ addSet(Set set)
+ isMatchOver(): boolean
+ getMatchScore(): String
}

class Player {
- int id
- String name
- int currentPoints **
- int[] gamesWonPerSet ****

+ scorePoint() **
}

class Referee {
- int id
- String name
- String password

+ authenticate(String password): boolean
}

class Set {
- int numberSet ++
- int playerServiceGamesWon
- int playerRestGamesWon

+ isSetOver()
}

class Game {
- Player playerService
- Player playerRest

+ addPoint(Player player)
+ isGameOver(): boolean
- checkGameWinner(Player): boolean
- getOpponent(Player player): Player
}

class TieBreakGame {
- int playerServicePoints
- int playerRestPoints

+ addPoint(Player player)
+ checkTieBreakWinner(): boolean
+ getScore(): String
}

@enduml