@startuml
package "model" {

    class Match {
    - Date date
    - Player playerService
    - Player playerRest
    - boolean isPlayerService
    - Game currentGame

    + startNewGame()
    + addSet(Set set)
    + isMatchOver(): boolean
    + getMatchScore(): String
    + switchRoles()
    }

    class Referee {
    - int id
    - String name
    - String password

    + authenticate(String password): boolean
    }

    class Player {
    - int id
    - String name
    - int currentPoints

    + scorePoint()
    }

    class Set {
    - int playerServiceGamesWon
    - int playerRestGamesWon

    + isSetOver()
    }

    class Game {
    - Player playerService
    - Player playerRest

    + addPoint(Player player)
    + isGameOver(): boolean
    - checkGameWinner(Player): boolean
    - getOpponent(Player player): Player
    }

    class TieBreakGame {
    - int playerServicePoints
    - int playerRestPoints

    + addPoint(Player player)
    + checkTieBreakWinner(): boolean
    + getScore(): String
    }
}

package "view" {
    class MatchView {

    + displayInitialMatch(ScoreController scoreController)
    + displayMatchScore(ScoreController scoreController)
    + displayMatchResult(ScoreController scoreController)
    + displayPlayerCreated(Player player)
    + displaySetOver()
    + displayMatchOver(
    }

    class RefereeView {

    + displayRefereeCreated(Referee referee)
    + displayLoginStatus(boolean success)
    }

    class ScoreView {

    + displayPointToServer(Player playerService)
    + displayPointToReceiver(Player playerRest)
    + displayLackService(Player playerService)
    + displayGameOver()
    }

}

package "controller" {
    class MatchController {
    - ScoreController scoreController
    - MatchView matchView
    - ScoreView scoreView
    - Match match

    + createMatch(int totalSets, Player playerCurrent, Player playerPast)
    + getInitialMatch()
    + getDisplayMatchScore()
    + lackService()
    + pointService()
    + pointRest()
    }

    class PlayerController {
    - List<Player> players

    + createPlayer(String name): Player
    + getPlayerById(int id): Optional<Player>
    + getPlayers(): List<Player>
    }

    class RefereeController {
    - List<Referee> referees

    + createReferee(String name, String password): Referee
    + login(String name, String password): boolean
    - isDuplicate(String name, String password)
    }

    class ScoreController {
    - Match match
    - Player currentServer
    - Player playerService
    - int lackServiceCount

    + checkGameEndAndSwitchRoles()
    + pointService()
    + pointRest()
    + lackService()
    + isGameOver(): boolean
    - givePointToOponent()

    }
}

"controller" ..> "model" : request
"controller" ..> "view" : display
"view" ..> "controller" : request
"model" ..> "controller" : send


@enduml